name       = "forcad"
version    = "0.2.0"
license    = "BSD 3-Clause License"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2024, Seyed Ali Ghasemi"
categories = ["graphics"]
keywords   = ["Fortran", "CAD","NURBS", "b-spline","bezier","rational bezier","geometry"]

[build]
auto-executables = false
auto-tests       = true
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[[example]]
name       = "demo_curve"
source-dir = "example"
main       = "demo_curve.f90"

[[example]]
name       = "demo_surface"
source-dir = "example"
main       = "demo_surface.f90"

[[example]]
name       = "demo_volume"
source-dir = "example"
main       = "demo_volume.f90"

[[example]]
name       = "example_curve_1"
source-dir = "example"
main       = "example_curve_1.f90"

[[example]]
name       = "example_surface_1"
source-dir = "example"
main       = "example_surface_1.f90"

[[example]]
name       = "example_volume_1"
source-dir = "example"
main       = "example_volume_1.f90"

[[example]]
name       = "shape_hexahedron"
source-dir = "example"
main       = "shape_hexahedron.f90"

[[example]]
name       = "shape_circle"
source-dir = "example"
main       = "shape_circle.f90"

[[example]]
name       = "put_to_nurbs"
source-dir = "example"
main       = "put_to_nurbs.f90"