name       = "forcad"
version    = "0.1.0"
license    = "BSD 3-Clause License"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2024, Seyed Ali Ghasemi"
categories = ["graphics"]
keywords   = ["Fortran", "CAD","NURBS", "b-spline","bezier","rational bezier","geometry"]

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[[example]]
name       = "bezier_curve"
source-dir = "example"
main       = "bezier_curve.f90"

[[example]]
name       = "bezier_surface"
source-dir = "example"
main       = "bezier_surface.f90"

[[example]]
name       = "bezier_volume"
source-dir = "example"
main       = "bezier_volume.f90"

[[example]]
name       = "nurbs_curve"
source-dir = "example"
main       = "nurbs_curve.f90"

[[example]]
name       = "nurbs_surface"
source-dir = "example"
main       = "nurbs_surface.f90"

[[example]]
name       = "nurbs_volume"
source-dir = "example"
main       = "nurbs_volume.f90"